################################################################
# Global configuration
################################################################

debug = {{ .Env.DEBUG }}
logLevel = "{{ .Env.LOG_LEVEL }}"

defaultEntryPoints = ["https", "http"]

[entryPoints]

  {{if isTrue .Env.TRAEFIK_DASHBOARD_ENABLED }}
  [entryPoints.traefik]
  address = ":8080"
  compress = true
  {{end}}

  [entryPoints.http]
  address = ":80"
  compress = true
  {{if isTrue .Env.LETS_ENCRYPT_ENABLED }}
    [entryPoints.http.redirect]
    entrypoint = "https"

  [entryPoints.https]
  address = ":443"
  compress = true

    [entryPoints.https.tls]

    {{if isTrue .Env.HTTP_AUTH_ENABLED}}
    [entryPoints.https.auth.basic]
      users = ["{{ .Env.HTTP_AUTH_USER }}:{{ .Env.HTTP_AUTH_PASSWORD }}"]
    {{end}}
  {{end}}

[retry]

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
swarmMode = {{ .Env.SWARM_MODE }}

{{if isTrue .Env.LETS_ENCRYPT_ENABLED }}
################################################################
# Let's encrypt
################################################################

[acme]
email = "{{ .Env.ACME_EMAIL }}"
storage = "{{ .Env.ACME_STORAGE }}"
onHostRule = true
acmeLogging = true
entryPoint = "https"
{{if isTrue .Env.LETS_ENCRYPT_STAGING }}
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
{{end}}

  [acme.httpChallenge]
  entryPoint = "http"
{{end}}

{{if isTrue .Env.TRAEFIK_DASHBOARD_ENABLED }}
################################################################
# Traefik dashboard
################################################################

[api]
entryPoint = "traefik"
dashboard = true
debug = false
{{end}}
